// <auto-generated />
using System;
using DotnetProject.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetProject.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260912065953_InitialPhase2Migrations")]
    partial class InitialPhase2Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeploymentRecordId")
                        .HasColumnType("int");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentRecordId");

                    b.ToTable("DeploymentLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "dotnet restore completed in 1.82 seconds with 0 warnings.",
                            StepName = "Restore Dependencies",
                            Timestamp = new DateTime(2026, 8, 31, 16, 0, 5, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Test run passed! 8 tests passed, 0 failed, 0 skipped in 1.05 seconds.",
                            StepName = "Automated xUnit Test Gate",
                            Timestamp = new DateTime(2026, 8, 31, 16, 0, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Release binaries compiled and published to ./publish output directory.",
                            StepName = "Publish Artifacts",
                            Timestamp = new DateTime(2026, 8, 31, 16, 0, 28, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Binaries transferred via encrypted SCP to /var/www/dotnetapp on AWS EC2.",
                            StepName = "SCP Transfer",
                            Timestamp = new DateTime(2026, 8, 31, 16, 0, 40, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "sudo systemctl restart dotnetapp.service executed cleanly. Daemon active (running).",
                            StepName = "systemd Service Restart",
                            Timestamp = new DateTime(2026, 8, 31, 16, 0, 48, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeployedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ExecutionDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Deployments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppName = "DevOps Release Tracker",
                            CommitHash = "bc8d5e0",
                            DeployedAt = new DateTime(2026, 8, 31, 16, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "GitHub Actions CI/CD",
                            Environment = "Production",
                            ExecutionDurationSeconds = 48,
                            Notes = "Initial production deployment to AWS EC2 via systemd daemon and Nginx reverse proxy.",
                            ProjectId = 1,
                            Status = "Successful",
                            Version = "v1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            AppName = "DevOps Release Tracker",
                            CommitHash = "93bc198",
                            DeployedAt = new DateTime(2026, 9, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "GitHub Actions CI/CD",
                            Environment = "Staging",
                            ExecutionDurationSeconds = 42,
                            Notes = "Staging verification for decoupled REST API endpoints and Swagger UI.",
                            ProjectId = 1,
                            Status = "Successful",
                            Version = "v1.1.0-preview"
                        },
                        new
                        {
                            Id = 3,
                            AppName = "Payment & Billing Service",
                            CommitHash = "f4c9a82",
                            DeployedAt = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Platform Engineer",
                            Environment = "Production",
                            ExecutionDurationSeconds = 55,
                            Notes = "Stripe webhook retry exponential backoff optimization.",
                            ProjectId = 2,
                            Status = "Successful",
                            Version = "v2.3.1"
                        },
                        new
                        {
                            Id = 4,
                            AppName = "Notification Dispatcher Daemon",
                            CommitHash = "3e28b10",
                            DeployedAt = new DateTime(2026, 9, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Developer Local Runner",
                            Environment = "Development",
                            ExecutionDurationSeconds = 20,
                            Notes = "Testing RabbitMQ dead-letter exchange consumers.",
                            ProjectId = 3,
                            Status = "In-Progress",
                            Version = "v0.9.4"
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DevOps Release Tracker",
                            Owner = "Platform Engineering",
                            RepositoryUrl = "https://github.com/MarzanulHoque/dotnet-devops-release-tracker",
                            Slug = "release-tracker",
                            TechStack = "ASP.NET Core 8.0, Nginx, systemd, MySQL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Payment & Billing Service",
                            Owner = "FinTech Core",
                            RepositoryUrl = "https://github.com/company/payment-service",
                            Slug = "payment-service",
                            TechStack = ".NET 8 Web API, PostgreSQL, Stripe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Notification Dispatcher Daemon",
                            Owner = "Messaging Infrastructure",
                            RepositoryUrl = "https://github.com/company/notification-worker",
                            Slug = "notification-daemon",
                            TechStack = "Go 1.22, RabbitMQ, Redis"
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentLog", b =>
                {
                    b.HasOne("DotnetProject.Core.Entities.DeploymentRecord", "DeploymentRecord")
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentRecord");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.HasOne("DotnetProject.Core.Entities.Project", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.Project", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
