// <auto-generated />
using System;
using DotnetProject.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetProject.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916071718_AddPhase2ExpandedSeedData")]
    partial class AddPhase2ExpandedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeploymentRecordId")
                        .HasColumnType("int");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentRecordId");

                    b.ToTable("DeploymentLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "dotnet restore completed in 1.82 seconds with 0 warnings.",
                            StepName = "Restore Dependencies",
                            Timestamp = new DateTime(2026, 9, 9, 12, 0, 5, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Test run passed! 16 tests passed, 0 failed, 0 skipped in 1.05 seconds.",
                            StepName = "Automated xUnit Test Gate",
                            Timestamp = new DateTime(2026, 9, 9, 12, 0, 18, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Release binaries compiled and published to ./publish output directory.",
                            StepName = "Publish Artifacts",
                            Timestamp = new DateTime(2026, 9, 9, 12, 0, 28, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "Binaries transferred via encrypted SCP to /var/www/dotnetapp on AWS EC2.",
                            StepName = "SCP Transfer",
                            Timestamp = new DateTime(2026, 9, 9, 12, 0, 40, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            DeploymentRecordId = 1,
                            LogLevel = "Info",
                            Message = "sudo systemctl restart dotnetapp.service executed cleanly. Daemon active (running).",
                            StepName = "systemd Service Restart",
                            Timestamp = new DateTime(2026, 9, 9, 12, 0, 48, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            DeploymentRecordId = 5,
                            LogLevel = "Info",
                            Message = "EF Core Migration applied to MySQL 8.0 disk storage (__EFMigrationsHistory updated).",
                            StepName = "Database Migration",
                            Timestamp = new DateTime(2026, 9, 12, 11, 0, 10, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            DeploymentRecordId = 5,
                            LogLevel = "Info",
                            Message = "DynamicUser=yes and ProtectSystem=strict verified active in kernel cgroup.",
                            StepName = "systemd Sandboxing Verification",
                            Timestamp = new DateTime(2026, 9, 12, 11, 0, 22, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            DeploymentRecordId = 5,
                            LogLevel = "Info",
                            Message = "Reverse proxy routes verified: / -> Kestrel :5000, /api/ -> Kestrel :5050 (HTTP 200 OK).",
                            StepName = "Nginx Proxy Upstream Check",
                            Timestamp = new DateTime(2026, 9, 12, 11, 0, 38, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            DeploymentRecordId = 8,
                            LogLevel = "Info",
                            Message = "Terraform applied 4 resources: aws_security_group_rule, aws_route_table. 0 failed.",
                            StepName = "Terraform Apply",
                            Timestamp = new DateTime(2026, 9, 12, 14, 10, 55, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeployedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ExecutionDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Deployments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppName = "DevOps Release Tracker",
                            CommitHash = "bc8d5e0",
                            DeployedAt = new DateTime(2026, 9, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "GitHub Actions CI/CD",
                            Environment = "Production",
                            ExecutionDurationSeconds = 48,
                            Notes = "Initial production deployment to AWS EC2 via systemd daemon and Nginx reverse proxy.",
                            ProjectId = 1,
                            Status = "Successful",
                            Version = "v1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            AppName = "DevOps Release Tracker",
                            CommitHash = "93bc198",
                            DeployedAt = new DateTime(2026, 9, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "GitHub Actions CI/CD",
                            Environment = "Staging",
                            ExecutionDurationSeconds = 42,
                            Notes = "Staging verification for decoupled REST API endpoints and Swagger UI.",
                            ProjectId = 1,
                            Status = "Successful",
                            Version = "v1.1.0-preview"
                        },
                        new
                        {
                            Id = 3,
                            AppName = "Payment & Billing Gateway",
                            CommitHash = "f4c9a82",
                            DeployedAt = new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "FinTech SRE",
                            Environment = "Production",
                            ExecutionDurationSeconds = 55,
                            Notes = "Stripe webhook retry exponential backoff optimization.",
                            ProjectId = 2,
                            Status = "Successful",
                            Version = "v2.3.1"
                        },
                        new
                        {
                            Id = 4,
                            AppName = "Notification Dispatcher Daemon",
                            CommitHash = "3e28b10",
                            DeployedAt = new DateTime(2026, 9, 12, 4, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Developer Local Runner",
                            Environment = "Development",
                            ExecutionDurationSeconds = 20,
                            Notes = "Testing RabbitMQ dead-letter exchange consumers.",
                            ProjectId = 3,
                            Status = "In-Progress",
                            Version = "v0.9.4"
                        },
                        new
                        {
                            Id = 5,
                            AppName = "DevOps Release Tracker",
                            CommitHash = "18e0827",
                            DeployedAt = new DateTime(2026, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "GitHub Actions [CI/CD]",
                            Environment = "Production",
                            ExecutionDurationSeconds = 38,
                            Notes = "Phase 2 True 3-Tier Architecture live on AWS EC2 with systemd sandboxing.",
                            ProjectId = 1,
                            Status = "Successful",
                            Version = "v2.0.0"
                        },
                        new
                        {
                            Id = 6,
                            AppName = "Auth & Identity Provider",
                            CommitHash = "a9b8c7d",
                            DeployedAt = new DateTime(2026, 9, 12, 12, 15, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Security Automation",
                            Environment = "Production",
                            ExecutionDurationSeconds = 44,
                            Notes = "OAuth2 refresh token rotation and rate limiting enabled.",
                            ProjectId = 4,
                            Status = "Successful",
                            Version = "v1.2.0"
                        },
                        new
                        {
                            Id = 7,
                            AppName = "Telemetry & Metrics Collector",
                            CommitHash = "7e6d5c4",
                            DeployedAt = new DateTime(2026, 9, 12, 13, 40, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "SRE Pipeline",
                            Environment = "Production",
                            ExecutionDurationSeconds = 29,
                            Notes = "Scraping Kestrel endpoints at /api/health with 15s interval.",
                            ProjectId = 5,
                            Status = "Successful",
                            Version = "v1.0.4"
                        },
                        new
                        {
                            Id = 8,
                            AppName = "Cloud Infrastructure & IaC Engine",
                            CommitHash = "c1e8b93",
                            DeployedAt = new DateTime(2026, 9, 12, 14, 10, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Terraform Cloud",
                            Environment = "Production",
                            ExecutionDurationSeconds = 64,
                            Notes = "AWS EC2 security group ingress tightening and VPC peering verification.",
                            ProjectId = 6,
                            Status = "Successful",
                            Version = "v2.1.0"
                        },
                        new
                        {
                            Id = 9,
                            AppName = "Customer Web Experience Portal",
                            CommitHash = "2d4f8a1",
                            DeployedAt = new DateTime(2026, 9, 12, 14, 50, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Frontend CI Bot",
                            Environment = "Production",
                            ExecutionDurationSeconds = 31,
                            Notes = "React 19 SPA asset bundle CDN cache invalidation and deploy.",
                            ProjectId = 7,
                            Status = "Successful",
                            Version = "v3.4.0"
                        },
                        new
                        {
                            Id = 10,
                            AppName = "Payment & Billing Gateway",
                            CommitHash = "5b3e901",
                            DeployedAt = new DateTime(2026, 9, 12, 15, 20, 0, 0, DateTimeKind.Utc),
                            DeployedBy = "Release Engineer",
                            Environment = "Staging",
                            ExecutionDurationSeconds = 36,
                            Notes = "Staging smoke tests passed for payment gateway failover.",
                            ProjectId = 2,
                            Status = "Successful",
                            Version = "v2.3.2-patch"
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DevOps Release Tracker",
                            Owner = "Platform Engineering",
                            RepositoryUrl = "https://github.com/MarzanulHoque/dotnet-devops-release-tracker",
                            Slug = "release-tracker",
                            TechStack = "ASP.NET Core 8.0, Nginx, systemd, MySQL"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Payment & Billing Gateway",
                            Owner = "FinTech Core",
                            RepositoryUrl = "https://github.com/enterprise/payment-gateway",
                            Slug = "payment-gateway",
                            TechStack = ".NET 8 Web API, PostgreSQL, Stripe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Notification Dispatcher Daemon",
                            Owner = "Messaging Infrastructure",
                            RepositoryUrl = "https://github.com/enterprise/notification-worker",
                            Slug = "notification-daemon",
                            TechStack = "Go 1.22, RabbitMQ, Redis"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Auth & Identity Provider",
                            Owner = "Security Core",
                            RepositoryUrl = "https://github.com/enterprise/auth-service",
                            Slug = "auth-identity",
                            TechStack = "ASP.NET Core 8.0, OIDC, OpenIddict"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Telemetry & Metrics Collector",
                            Owner = "Observability SRE",
                            RepositoryUrl = "https://github.com/enterprise/telemetry-agent",
                            Slug = "telemetry-collector",
                            TechStack = "OpenTelemetry, Prometheus, Grafana"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cloud Infrastructure & IaC Engine",
                            Owner = "Cloud Operations",
                            RepositoryUrl = "https://github.com/enterprise/cloud-terraform",
                            Slug = "cloud-iac-engine",
                            TechStack = "Terraform, AWS, Ansible, GitHub Actions"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Customer Web Experience Portal",
                            Owner = "Frontend Experience",
                            RepositoryUrl = "https://github.com/enterprise/customer-web",
                            Slug = "customer-portal",
                            TechStack = "React 19, TypeScript, Vite, Tailwind CSS"
                        });
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentLog", b =>
                {
                    b.HasOne("DotnetProject.Core.Entities.DeploymentRecord", "DeploymentRecord")
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentRecord");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.HasOne("DotnetProject.Core.Entities.Project", "Project")
                        .WithMany("Deployments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.DeploymentRecord", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DotnetProject.Core.Entities.Project", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
